# Generated by Django 4.2.5 on 2023-09-21 05:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_file',
            field=models.FileField(default='', storage=home.models.VideoStorage(), upload_to='videos/'),
        ),
    ]
